application: remail-taskforce
version: py27
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: yaml
  version: "3.10"

handlers:
- url: /_ah/mail/.+
  script: main.app
  login: admin
- url: .*
  script: main.app

inbound_services:
- mail

builtins:
- deferred: on
